"""
Auto-generated by autonomous agents
Source: batch_1_20260501_060658.txt
Category: misc
"""

# Production-ready Implementation of Smart Retry Logic

import asyncio

import httpx


class SmartRetrier:
    """
    A class to implement smart retry logic for HTTP request. It handles exponential backoff
    and includes detailed error handling.


    Example Usage:
    async def process_url(url: str) -> None:
        retrier = SmartRetrier()
        response = await retrier.fetch_data(url)
        print(response.text if response else "Request failed after all retries.")
    """

    def __init__(self, base_url: str, max_retries: int = 3) -> None:
        self.base_url = base_url
        self.max_retries = max_retries

    async def _fetch_data(self, url: str, sleep_time: float = 1.0) -> httpx.Response:
        """Fetches data from the given URL.
        Implements exponential backoff retry logic up to a maximum number of attempts."""

        if not url.startswith("http"):
            url = self.base_url + url

        response = None
        tries_remaining = self.max_retries
        sleep_time = 2**tries_remaining  # Exponential backoff

        async with httpx.AsyncClient() as client:
            while tries_remaining > 0:
                try:
                    response = await client.get(url)
                    response.raise_for_status()  # Raises for HTTP errors if there is a bad request, etc.
                    return response
                except (httpx.HTTPError, ValueError):
                    print(f"Request failed. Retrying in {sleep_time:.1f} seconds...")
                    await asyncio.sleep(sleep_time)
                    tries_remaining -= 1

        raise Exception("Max retries reached and no success. Aborting.")

    async def fetch_data(self, url: str) -> httpx.Response:
        """Primary method to be used externally. It encapsulates the internal logic of fetching data.

        Arguments:
            url: The full URL for the request.

        Returns:
            A `httpx.Response` object or an exception on failure."""
        url = self.base_url + url  # Ensures valid url format
        return await self._fetch_data(url=url)


# Example usage
async def process_url(urls_to_process: list) -> None:
    """Processes a list of URLs concurrently. It retries failed requests up to max_retries times.

    Arguments:
        urls_to_process (list): A list of URL strings."""

    async def fetch_and_print(url: str):
        try:
            retrier = SmartRetrier(url)
            response = await retrier.fetch_data(url)
            print(f"Success: {url}")
        except Exception as e:
            print(str(e))

    await asyncio.gather(*(fetch_and_print(url) for url in urls_to_process))


# Example check function
async def check_function():
    smart_retrier = SmartRetrier("https://example.invalid/endpoint/")
    try:
        # Simulate request which could fail, for example, due to timeout.
        # Note: In real production, use proper url joining.
        response = await smart_retrier.fetch_data("verywrongurl")
        if response.status_code == 404 or "unreachable" in str(response.content):
            print("Simulated failure.")
    except Exception as e:
        print(f"Caught exception: {str(e)}")
    else:
        print("Success, no need for retries.")


async def main():
    # Example usage for demonstration.
    pass

if __name__ == "__main__":
    asyncio.run(main())
