"""
Auto-generated by autonomous agents
Source: batch_1_20260503_044838.txt
Category: api
"""

import requests
from abc import ABC, abstractmethod


class WebhookNotificationManager(ABC):
    """
    Abstract class for managing webhooks. Subclasses provide specific implementations of different notification channels.
    """

    @abstractmethod
    def send(self, message):
        """
        Sends a webhook notification with the provided `message`.
        
        Args:
            message (str): The content to be sent in the notification payload.

        Raises:
            Exception: If an error is encountered while sending the notification.
        """


class EmailWebhookNotificationManager(WebhookNotificationManager):
    def __init__(self, email_service_url):
        self.email_service_url = email_service_url

    def send(self, message):
        try:
            response = requests.post(url=self.email_service_url, json={'message': message})
            response.raise_for_status()
        except requests.RequestException as e:
            raise Exception(f"Failed to send webhook notification: {e}")


def create_webhook_notification_manager(warning_type='email', email_service_url='') -> WebhookNotificationManager:
    """
    Factory function to create an instance of a specific webhook notification manager for the requested `warning_type`.

    Args:
        warning_type (str): The type of warning, which should match one of the supported types in WebhookNotificationManager subclasses.
            Valid values include: 'email'.
        email_service_url (str): URL for the email service. Required if using the 'email' warning type.

    Returns:
        WebhookNotificationManager: An instance of a specific implementation of WebhookNotificationManager, based on `warning_type`.

    Raises:
        ValueError: If an unsupported `warning_type` is provided.
        ValueError: If no default URL is provided and there is no email_service_url parameter for the supported `warning_type`.
    """
    if warning_type == 'email':
        if not email_service_url:
            raise ValueError("Email service URL must be specified when using email as the warning type.")
        return EmailWebhookNotificationManager(email_service_url)
    else:
        raise ValueError(f"Unsupported message type: {warning_type}")


# Example Usage
def example_usage():
    # Create a notification manager for sending an email alert
    webhook_manager = create_webhook_notification_manager(warning_type='email', email_service_url='https://api.emailservice.com/webhooks')
    
    print("Notification Manager Created Successfully")
    webhook_manager.send(message="A generic warning message to notify of something important and urgent.")


if __name__ == "__main__":
    example_usage()

import unittest

class TestWebhookManager(unittest.TestCase):
    def test_create_webhook_manager(self):
        with self.assertRaises(ValueError):
            create_webhook_notification_manager(warning_type='sms')  # Ensure that an unsupported warning type fails gracefully.

        email_service_url = 'https://api.emailservice.com/webhooks'
        webhook_manager = create_webhook_notification_manager(warning_type='email', email_service_url=email_service_url)
        
        self.assertIsInstance(webhook_manager, EmailWebhookNotificationManager)
        with self.assertRaises(ValueError):
            create_webhook_notification_manager(warning_type='sms')  # Ensure no sms service url provided fails.

        webhook_manager.send(message="Test Webhook")


if __name__ == '__main__':
    unittest.main()
