"""
Auto-generated by autonomous agents
Source: batch_1_20260501_055638.txt
Category: api
"""

import requests

class WebhookNotifier:
    """
    A class to handle creating and managing webhook notifications. 
    It includes methods for sending notifications using GET or POST webhooks.
    
    Attributes:
        url (str): The URL of the webhook endpoint.
        headers (dict): Headers to include with the HTTP request.
        event_type (str): The specific event type to notify about.
        
    Methods:
        send_notification(signal): Sends a notification signal via the configured webhook.
    """

    def __init__(self, url: str, headers: dict = None, event_type: str = ''):
        """
        Initializes the WebhookNotifier with the given URL and optional headers and event type.

        Args:
            url (str): The URL of the webhook endpoint to send notifications to.
            headers (dict, optional): Headers to include in the HTTP request. Defaults to None.
            event_type (str, optional): Specific event type to notify about. Defaults to ''.
        """
        self.url = url
        if headers:
            self.headers = headers
        else:
            self.headers = {'Content-Type': 'application/json'}
        self.event_type = event_type

    def send_notification(self, payload: dict):
        """
        Sends a notification signal through the configured webhook. Payload is sent in JSON format.

        Args:
            payload (dict): The data to include in the HTTP request body as a json object.
        
        Returns:
            requests.Response: A Response object containing the response from the webhook endpoint.
            
        Raises:
            Exception: If there is an issue with sending the notification. 
                This could be due to network errors or invalid URL format.
        """
        try:
            response = requests.request('POST' if self.event_type else 'GET', self.url, headers=self.headers, json=payload)
            response.raise_for_status()
        except requests.exceptions.RequestException as e:
            raise Exception(f"Error sending notification: {e}")
        return response

# Example Usage
if __name__ == "__main__":
    NOTIFICATION_URL = "https://example.com/api/webhooks/notification"
    payload_example = {'severity': 'high', 'alert_time': '2023-10-05T09:00:00Z'}
    webhook_notifier = WebhookNotifier(NOTIFICATION_URL)
    
    # Example 1 - Non-event specific notification (GET request)
    print("Sending GET Request Notification:", webhook_notifier.send_notification(payload_example))
    
    # Example 2 - Event-specific notification
    event_specific_payload_example = {'severity': 'high', 'alert_time': '2023-10-05T09:00:00Z', 'event_type': 'security_alert'}
    webhook_notifier.event_type = 'security_alert'
    print("Sending POST Request Notification (Specific Event Type):", webhook_notifier.send_notification(event_specific_payload_example))


# Function to test the WebhookNotifier class.
def test_webhook_notifier():
    NOTIFICATION_URL = "https://test-notification-url.com"
    
    # Check that GET notification works correctly
    notifier_get = WebhookNotifier(NOTIFICATION_URL)
    response_mock_get = {'status': 'success'}
    assert notifier_get.send_notification({'key1': 'value1'}).json() == response_mock_get
    
    # Check that POST notification of specific event type works correctly.
    event_payload_example = {'key2': True, 'event_type': 'test_event'}
    post_notifer = WebhookNotifier(NOTIFICATION_URL, headers={'X-Custom-Header': 'customValue'}, event_type='test_event')
    response_mock_post = {'status': 'success', 'event': 'test_event'}  
    assert post_notifer.send_notification(event_payload_example).json() == response_mock_post

# Run the test
if __name__ == "__main__":
    test_webhook_notifier()
