"""
Auto-generated by autonomous agents
Source: batch_1_20260501_123039.txt
Category: api
"""

import requests

class WebhookNotifications:
    """
    A class to handle webhook notifications. It sends notification payloads to configured endpoints via webhooks.
    
    Attributes:
        api_key (str): The API key used for authentication in the request headers.
        endpoint_url (str): The URL of the webhook endpoint where the notification payload will be sent.

    Methods:
        send_notification(payload, url): Send a JSON-encoded payload to a specified endpoint.
        _validate_payload(payload): Validate that the provided payload is a dictionary and not empty.
        _validate_api_key(api_key): Check if the API key meets security requirements (e.g., length, complexity).
        _validate_endpoint_url(url): Ensure the URL format is correct for webhooks.
    """
    
    def __init__(self, api_key: str, endpoint_url: str):
        self.api_key = api_key
        self.endpoint_url = endpoint_url
    
    @staticmethod
    def send_notification(payload, url: str) -> None:
        """ Sends a JSON payload to the specified URL via POST request.
        
        Args:
            payload (dict): The notification payload that is sent as body of the HTTP requests. 
                It must be a dictionary and not empty.
            url (str): The webhook endpoint URL where the received payload should be forwarded.

        Returns:
            None: This method does not return anything, it only sends the payload.

        Raises:
            ValueError: If the provided payload is missing.
            RuntimeError: If the API key or the provided URL doesn't validate correctly. 
            
        Example usage:
            api = WebhookNotifications(api_key='12345', endpoint_url='https://example.com/webhook')
            api.send_notification({'event': 'user.login'}, 'https://third-party-site.com/payload-forwarder')  # Send event to third-party site
        """
        
        if not payload or not isinstance(payload, dict):
            raise ValueError("Payload must be a non-empty dictionary.")
        
        WebhookNotifications._validate_api_key(api_key=self.api_key)
        WebhookNotifications._validate_endpoint_url(url=url)
        
        try:
            response = requests.post(
                url=url,
                headers={'Authorization': f'Bearer {self.api_key}'},  # Ensure secure key transmission
                json=payload,  # Convert payload to JSON format automatically by the requests library
            )
            response.raise_for_status()  # Raise an HTTPError if a server error occurred.
        except Exception as e:
            raise RuntimeError(f"Failed sending notification: {str(e)}")

    @staticmethod
    def _validate_payload(payload):
        """ Validates that the provided payload is valid for this webhook feature. """
        if not isinstance(payload, dict) or payload == {}:
            raise ValueError("Payload must be a non-empty dictionary.")
        
    @staticmethod
    def _validate_api_key(api_key: str) -> None:
        """ Validates the API key to ensure it meets security requirements (e.g., length and complexity). """
        if not api_key or len(api_key.strip()) <= 6:
            raise RuntimeError("API Key is invalid. Please provide a unique string longer than 5 characters.")
        
    @staticmethod
    def _validate_endpoint_url(url: str) -> None:
        """ Validates the endpoint URL to ensure its format is correct for webhooks. """
        if not url or "://" in url and len(url.split('//')) == 2:
            raise ValueError("The provided webhook URL does not appear valid.")
        
# Example Usage
if __name__ == "__main__":
    WEBHOOK_API_KEY = 'abc123'
    WEBHOOK_ENDPOINT = 'https://mywebhook.com/event'

    # Create an instance of WebhookNotifications to send notifications.
    webhook_notifications = WebhookNotifications(api_key=WEBHOOK_API_KEY, endpoint_url=WEBHOOK_ENDPOINT)
    
    try:
        payload = {'name': 'Example Event', 'details': 'Notification sent from a Python web application.'}
        response = webhook_notifications.send_notification(payload=payload, url=WEBHOOK_NOTIFICATIONS.endpoint_url)  
        # Example return would be None as there's no direct return but the notification can be checked on the given endpoint.
    except RuntimeError as e:
        print(e)
