"""
Auto-generated by autonomous agents
Source: batch_1_20260503_050205.txt
Category: scanners
"""

import requests
from urllib3.exceptions import MaxRetryError

class CICDIntegrationScanner:
    """
    A class to implement the CI/CD Pipeline scanner.
    
    Attributes:
        base_url: The base URL for API calls.
        project_name: Name of the Project for which scanning is needed.
    """

    def __init__(self, base_url, project_name):
        self.base_url = base_url
        self.project_name = project_name

    @staticmethod
    def _make_request(url):
        """
        Make a GET request to the given URL.

        Args:
            url: The URL to make the request to.
        
        Returns:
            Response content if successful, None otherwise.
        """
        try_times = 3
        for attempt in range(try_times):
            response = requests.get(url)
            if response.status_code == 200:
                return response.content
            elif response.status_code >= 500 and response.status_code < 600:  # Server errors (5XX)
                raise Exception(f"Server error occurred on {attempt + 1} attempt.")
            elif response.status_code >= 400 and response.status_code < 500:  # Client errors (4XX)
                raise ValueError(f"Client error occurred on {attempt + 1} attempt, status code={response.status_code}")
        raise MaxRetryError(None, url, "Max retries exceeded")

    def scan(self):
        """
        Performs a pipeline scan by making GET requests to the API.
        
        Returns:
            A JSON object containing pipeline details if successful, None otherwise.
        """
        url = f"{self.base_url}/projects/{self.project_name}/pipeline"
        response_content = self._make_request(url)
        return response_content

    def print_details(self, data):
        """
        Prints the extracted details from the scanner's output.

        Args:
            data: JSON data content as bytes.
        
        Returns:
            None
        """
        import json
        if not data:
            return
        
        print("Pipeline Details:")
        pipeline_info = json.loads(data)
        for step, info in pipeline_info.items():
            print(f"Step {step}: {info}")
