"""
Auto-generated by autonomous agents
Source: batch_1_20260501_122927.txt
Category: scanners
"""

#!/usr/bin/env python3

"""
Create XXE (XML External Entity) Scanner:
=====================================

This script acts as an XML External Entity (XXE) scanner.
It checks if there are any potential security vulnerabilities in the supplied XML documents by checking for external entity references.

Usage:
------
To run the scanner on a directory containing multiple XML files, use:

python xxe_scanner.py --directory 'path_to_directory'

For single file scanning, instead of using `--directory`, you can specify the path directly:

python xxe_scanner.py --file 'path_to_single_xml_file.xml'
"""

import os
import xml.etree.ElementTree as ET

class XeScanner:
    def __init__(self, directory=None, xml_file=None):
        self._xml_files = []
        
        if directory and os.path.exists(directory) and os.path.isdir(directory):
            for root, _, files in os.walk(directory):
                for file_name in files:
                    abs_path = os.path.join(root, file_name)
                    self._xml_files.append(abs_path)
        else: 
            if xml_file is not None:
                self._xml_files.append(xml_file)

    def _scan_xml(self, xml_path):
        try:
            tree = ET.parse(xml_path, ET.XMLReader())
            parser = tree.getroot().is_defaultnamespace
            return xml_path if parser else False
        except Exception as e:
            # Handle different types of exceptions gracefully.
            print(f"An error occurred during XML parsing for {xml_path}: {e}")
    
    def scan(self):
        results = {}
        
        for file in self._xml_files:
            found_xxe = self._scan_xml(file)
            if found_xe:
                results[file] = "XXE detected"
                
        return results

def main():
    import argparse
    parser = argparse.ArgumentParser(
        description='XSS Scanner: Check XML External Entities'
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--file', help="Path to a single xml file")
    group.add_argument('--directory', type=str, help="Directory with multiple xml files")

    args = parser.parse_args()

    scanner = XeScanner(args.file, args.directory)
    
    if not isinstance(scanner._xml_files, list):
        results = scanner.scan()
        for path in results:
            print(f"{path}: XXE detected")
    else:
        print("List of XML files provided as directory input. Review the scan results by running with file option.")

if __name__ == "__main__":
    main()

