"""
Auto-generated by autonomous agents
Source: batch_1_20260503_040428.txt
Category: reporting
"""

import os

from PIL import Image as PImage
from reportlab.lib.pagesizes import letter
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer


def generate_pdf_report(data_to_report):
    """
    Generates a PDF report based on the provided data.

    Args:
        data_to_report (dict): A dictionary containing structured data for the report.

    Returns:
        bytes: The PDF output of the report.

    Raises:
        ValueError: If the input is not a dict or contains non-string values.
    """
    doc = SimpleDocTemplate("report.pdf", pagesize=letter)

    story = []

    # Example format, replace with your data
    header1_paragraph = Paragraph("<font size='20'><b>Report Header</b></font>", style=H2_style)

    story.append(header1_paragraph)
    story.append(Spacer(1, 20))

    text_to_show = "Here is some sample text for the first section of the report."
    second_section_paragraph = Paragraph(text_to_show, style=NORMAL_STYLE)

    story.append(second_section_paragraph)
    story.append(Spacer(1, 25))

    # Example: Adding a picture
    image_path = "path/to/image.jpg"  # You should set this path to an actual valid image file.
    if not os.path.exists(image_path):
        raise ValueError(f"The specified image {image_path} does not exist.")
    img = PImage.open(image_path)

    resized_img = img.resize((150, 150))
    story.append(Image(str(resized_img), width=270, height=None))
    story.append(Spacer(1, 35))

    doc.build(story)


class H2_style:
    """A styled report lab 'Heading2' element."""

    borders = [0, 0, 0, 0]
    font = "Helvetica-Bold"
    fontSize = 14


class NORMAL_STYLE:
    """A default text style for normal paragraphs."""

    font = "Helvetica"
    fontSize = 12


# Example usage
if __name__ == "__main__":
    data_to_report = {
        "Date": "2023-10-05",
        "Status": "Completed",
        "Items_Found": ["Security issue #1", "Another security issue"],
    }

    pdf_bytes = generate_pdf_report(data_to_report)
    with open("report.pdf", "wb") as f:
        f.write(pdf_bytes)

# Test example
import unittest


class TestGeneratePDFReport(unittest.TestCase):
    def test_simple_data(self):
        generated_file_path = "test_result.pdf"
        result = generate_pdf_report({"Title": "Test Report", "Content": "This is a simple test."})
        with open(generated_file_path, "wb") as file:
            file.write(result)

        self.assertTrue(os.path.isfile(generated_file_path))
