#!/usr/bin/env python3
"""
Extract scanner code from batch outputs and organize into modules
"""

import os
import re
from pathlib import Path

# Create output directory
output_dir = Path("daqiq/scanners/generated")
output_dir.mkdir(parents=True, exist_ok=True)

# Scanner mappings
scanner_files = {
    "batch_1": ["xss_scanner.py", "sqli_scanner.py"],
    "batch_2": ["csrf_scanner.py", "path_traversal_scanner.py"],
    "batch_3": ["open_redirect_scanner.py", "xxe_scanner.py"],
}

# Read batch files
batch_dir = Path("output/scanner_modules")
batch_files = sorted(batch_dir.glob("batch_*.txt"))

print("🔍 Extracting scanner code from batches...\n")

for batch_file in batch_files:
    batch_num = re.search(r"batch_(\d+)", batch_file.name).group(1)

    print(f"📦 Processing {batch_file.name}")

    with open(batch_file, "r") as f:
        content = f.read()

    # Extract Python code blocks
    code_blocks = re.findall(r"```python\n(.*?)```", content, re.DOTALL)

    if code_blocks:
        batch_key = f"batch_{batch_num}"
        if batch_key in scanner_files:
            for i, code in enumerate(code_blocks):
                if i < len(scanner_files[batch_key]):
                    scanner_file = output_dir / scanner_files[batch_key][i]

                    # Write scanner code
                    with open(scanner_file, "w") as f:
                        f.write('"""\n')
                        f.write(f"Auto-generated by DAQIQ Autonomous Team\n")
                        f.write(f"Batch: {batch_num}\n")
                        f.write('"""\n\n')
                        f.write(code.strip())

                    print(f"  ✅ Created: {scanner_file.name}")
    else:
        print(f"  ⚠️  No code blocks found, saving raw output")
        raw_file = output_dir / f"batch_{batch_num}_raw.txt"
        with open(raw_file, "w") as f:
            f.write(content)
        print(f"  📄 Saved: {raw_file.name}")

print("\n" + "=" * 70)
print("✅ Scanner extraction complete!")
print("=" * 70)
print(f"📁 Location: {output_dir}")

# List what was created
print("\n📋 Generated scanner modules:")
for file in sorted(output_dir.glob("*.py")):
    size = file.stat().st_size
    print(f"  • {file.name} ({size} bytes)")

# Create __init__.py
init_file = output_dir / "__init__.py"
with open(init_file, "w") as f:
    f.write('"""Auto-generated DAQIQ Scanner Modules"""\n')

print(f"\n✨ Ready to use in DAQIQ framework!")
