"""
Auto-generated by autonomous agents
Source: batch_1_20260501_054834.txt
Category: reporting
"""


class ReportGenerator:
    def __init__(self, title):
        self.title = title
        self.body = []

    # other methods remain the same


def generate_example_report():
    content_body = [
        "The security team reviewed the systems for vulnerabilities.",
        "No critical issues were found,\n"
        "however some medium threats need further investigation.",
    ]
    return ReportGenerator("Monthly Security Audit").generate_pdf(content=content_body)


if __name__ == "__main__":
    report = generate_example_report()
