"""
Auto-generated by autonomous agents
Source: batch_1_20260503_043206.txt
Category: reporting
"""

import unittest

from executive_summary_generator import ExecutiveSummaryGenerator


class TestExecutiveSummaryGenerator(unittest.TestCase):
    def setUp(self) -> None:
        self.generator = ExecutiveSummaryGenerator()

    def test_generate_summary_empty_list(self):
        self.assertEqual(self.generator.generate_summary([]), "")

    def test_generate_summary_invalid_json(self):
        with self.assertRaises(ValueError) as context_manager:
            self.generator.generate_summary("{}")
        self.assertTrue(
            "Invalid JSON format in the security report." in str(context_manager.exception)
        )

    def test_generate_summary_normal_list(self):
        findings = [
            {
                "type": "infoleak",
                "location": "/userprofile/sensitive_file.txt",
                "description": "A secure credentials file readable by all users.",
            },
            {
                "type": "injection",
                "location": "/user/login.php?uname=admin&pwd=password",
                "description": "SQL injection vulnerability in user login page.",
            },
        ]
        expected_summary = "\n".join(
            [
                "**infoleak**: /userprofile/sensitive_file.txt           - A secure credentials file readable by all users.",
                "**injection**: /user/login.php?uname=admin&pwd=password    - SQL injection vulnerability in user login page.",
            ]
        )
        self.assertEqual(
            self.generator.generate_summary(json.dumps(findings)).strip(), expected_summary.strip()
        )


if __name__ == "__main__":
    unittest.main()
