#!/usr/bin/env python3
'''Extract and implement code from autonomous development batches'''

import os
import re
from pathlib import Path
from collections import defaultdict

def extract_code_from_batch(batch_file):
    '''Extract Python code blocks from a batch file'''
    with open(batch_file, 'r') as f:
        content = f.read()
    code_blocks = re.findall(r'```python\n(.*?)```', content, re.DOTALL)
    return code_blocks

def categorize_code(code_block):
    '''Categorize code by type'''
    code_lower = code_block.lower()
    if 'scanner' in code_lower:
        return 'scanners'
    elif 'detector' in code_lower:
        return 'detectors'
    elif 'analyzer' in code_lower or 'analysis' in code_lower:
        return 'analyzers'
    elif 'predictor' in code_lower or 'ml' in code_lower:
        return 'ml'
    elif 'report' in code_lower:
        return 'reporting'
    elif 'api' in code_lower:
        return 'api'
    else:
        return 'misc'

def extract_class_name(code_block):
    '''Extract the main class name from code'''
    match = re.search(r'class\s+(\w+)', code_block)
    return match.group(1) if match else 'UnknownClass'

def main():
    batch_dir = Path('autonomous_development')
    output_base = Path('src/daqiq/autonomous_generated')
    output_base.mkdir(parents=True, exist_ok=True)
    
    categories = ['scanners', 'detectors', 'analyzers', 'ml', 'reporting', 'api', 'misc']
    for cat in categories:
        (output_base / cat).mkdir(exist_ok=True)
        (output_base / cat / '__init__.py').touch()
    
    batch_files = sorted(batch_dir.glob('batch_*.txt'))
    print(f'📊 Found {len(batch_files)} batch files')
    
    generated_files = defaultdict(list)
    
    for batch_file in batch_files:
        code_blocks = extract_code_from_batch(batch_file)
        
        for code_block in code_blocks:
            if len(code_block) < 500:
                continue
            
            category = categorize_code(code_block)
            class_name = extract_class_name(code_block)
            filename = f'{class_name.lower()}.py'
            filepath = output_base / category / filename
            
            if filepath.exists():
                continue
            
            with open(filepath, 'w') as f:
                f.write('"""\n')
                f.write(f'Auto-generated by autonomous agents\n')
                f.write(f'Source: {batch_file.name}\n')
                f.write(f'Category: {category}\n')
                f.write('"""\n\n')
                f.write(code_block)
            
            generated_files[category].append(filename)
    
    print('\n✅ Code Implementation Complete!')
    print('\n📁 Generated Files by Category:')
    for category, files in generated_files.items():
        print(f'  {category}: {len(files)} files')
        for f in files[:3]:
            print(f'    - {f}')
        if len(files) > 3:
            print(f'    ... and {len(files)-3} more')
    
    print(f'\n📍 All files saved to: {output_base}')

if __name__ == '__main__':
    main()
