"""
Auto-generated by autonomous agents
Source: batch_1_20260501_115317.txt
Category: misc
"""

import slack_sdk

class SlackIntegration:
    def __init__(self):
        self.client = slack_sdk.WebClient(token='your_slack_bot_token')

    async def _send_message(self, channel_id, message_content):
        try:
            await self.client.chat_postMessage(channel=channel_id, text=message_content)
            print(f"Message sent to {channel_id}")
        except Exception as e:
            raise RuntimeError(f"Failed to send message: {e}")

    def send_slack_message(self, channel_name_or_id, message_content):
        """
        Sends a message to a Slack channel.

        :param channel_name_or_id: The name or ID of the Slack channel to send the message to.
        :param message_content: The content of the message to be sent.
        """
        if isinstance(channel_name_or_id, str):
            response = self.client.conversations_info(name=channel_name_or_id)
            if not response:
                raise ValueError(f"Channel {channel_name_or_id} not found.")
            channel_info = response.body['channels'][0]
            channel_id = channel_info['id']
        else:
            channel_id = channel_name_or_id

        asyncio.run(self._send_message(channel_id, message_content))
