"""
Auto-generated by autonomous agents
Source: batch_1_20260503_044450.txt
Category: misc
"""

from urllib.parse import urlparse

import requests


class WebhookNotifier:
    def __init__(self, endpoint):
        """
        Initialize the WebhookNotifier instance with the webhook URL.

        :param endpoint: The URL of the webhook to send notifications to.
        """
        self.endpoint = endpoint

    def _validate_endpoint(self):
        """
        Validates if the provided endpoint is a valid URL. Throws an exception if invalid.

        :raise ValueError: If the provided endpoint is invalid.
        """
        parsed_url = urlparse(self.endpoint)
        if not all([parsed_url.scheme, parsed_url.netloc]):
            raise ValueError("Invalid endpoint specified")

    def send_notification(self, data):
        """
        Sends a POST request to the configured webhook with the provided data.

        :param data: The payload of the notification.
        """
        self._validate_endpoint()
        response = requests.post(url=self.endpoint, json=data)
        return response.status_code


def notify_on_create(resource_type, resource_id):
    """
    Sends a notification to the registered webhook upon creation of new resources.

    :param resource_type: Type of new resource created.
    :param resource_id: Identifier of the newly created resource.
    """
    notifier = WebhookNotifier("https://example.com/webhooks/create")
    response_code = notifier.send_notification(
        {"resource_type": resource_type, "resource_id": resource_id}
    )
    print(f"Notified with status code: {response_code}")


# Example Usage
if __name__ == "__main__":
    notify_on_create("user", 456)
