#!/usr/bin/env python3
# packages/cherenkov/dev_crew/autonomous_issue_swarm.py
"""
Autonomous Issue Swarm — perpetual loop driven by GitHub issues.

Two execution paths:
  scanner  → SwarmOrchestrator CWE pipeline (Ollama, judge gate, candidate file)
  sprint   → AutonomousSprint (Architect spec + Developer code + ValidationGate)

Both paths end with:
  - git branch + commit
  - gh pr create
  - gh issue comment
  - status:in-progress → status:done label swap

Batch size = 3 (same as CWE swarm). Poll interval = 5 min when empty.
"""

from __future__ import annotations

import asyncio
import logging
import os
import subprocess
from pathlib import Path

from cherenkov.dev_crew.github_issue_source import GitHubIssueSource, IssueTask
from cherenkov.dev_crew.swarm_orchestrator import CWESpec, SwarmOrchestrator

logger = logging.getLogger("cherenkov.swarm.issues")

BATCH_SIZE = int(os.getenv("SWARM_BATCH_SIZE", "3"))
POLL_INTERVAL = int(os.getenv("SWARM_POLL_INTERVAL", "300"))  # seconds
MAIN_BRANCH = os.getenv("SWARM_MAIN_BRANCH", "main")

# Label constants
LABEL_IN_PROGRESS = "status:in-progress"
LABEL_DONE = "status:done"


class AutonomousIssueSwarm:
    """
    Polls GitHub issues and dispatches them to the correct execution pipeline.
    Runs forever: fetch → batch → execute → PR → sleep → repeat.
    """

    def __init__(self, repo: str = "") -> None:
        self.source = GitHubIssueSource(repo=repo)
        self.orchestrator = SwarmOrchestrator()
        self.repo = repo

    # ── Public API ───────────────────────────────────────────────────────────

    async def run_forever(self) -> None:
        logger.info(
            "AutonomousIssueSwarm started. batch=%d poll=%ds",
            BATCH_SIZE,
            POLL_INTERVAL,
        )
        while True:
            tasks = self.source.fetch_pending(limit=BATCH_SIZE * 4)
            if not tasks:
                logger.info("No actionable issues. Sleeping %ds.", POLL_INTERVAL)
                await asyncio.sleep(POLL_INTERVAL)
                continue

            batch = tasks[:BATCH_SIZE]
            logger.info(
                "Dispatching batch of %d issue(s): %s",
                len(batch),
                [f"#{t.number}" for t in batch],
            )
            # Mark all as in-progress before starting (prevents double-pick)
            for task in batch:
                self._mark_in_progress(task)

            results = await asyncio.gather(
                *[self._execute(task) for task in batch],
                return_exceptions=True,
            )
            self._report(batch, results)
            await asyncio.sleep(5)

    # ── Dispatch ─────────────────────────────────────────────────────────────

    async def _execute(self, task: IssueTask) -> bool:
        try:
            if task.kind == "scanner":
                return await self._run_scanner(task)
            elif task.kind == "sprint":
                return await self._run_sprint(task)
            return False
        except Exception as exc:
            logger.error("Issue #%d crashed: %s", task.number, exc, exc_info=True)
            self._mark_failed(task, str(exc))
            return False

    # ── Scanner path ─────────────────────────────────────────────────────────

    async def _run_scanner(self, task: IssueTask) -> bool:
        """Extract CWE info from title/labels and run the Ollama pipeline."""
        import re

        cwe_match = re.search(r"CWE-(\d+)", task.title, re.IGNORECASE)
        cwe_id = f"CWE-{cwe_match.group(1)}" if cwe_match else f"CWE-ISSUE-{task.number}"
        description = task.description

        spec = CWESpec(cwe_id=cwe_id, description=description)
        result = await self.orchestrator._process_cwe(spec)

        if result.success:
            pr_url = self._open_pr_for_scanner(task, result.module_name, cwe_id)
            self._mark_done(task, pr_url)
            return True

        self._mark_failed(task, result.fail_reason)
        return False

    def _open_pr_for_scanner(self, task: IssueTask, module_name: str, cwe_id: str) -> str:
        candidate = Path("candidates/generated_scanners") / f"{module_name}.py"
        dest = Path("packages/cherenkov/scanners") / f"{module_name}.py"

        ok = self._git_commit_file(
            src=candidate,
            dest=dest,
            branch=task.branch,
            commit_msg=(
                f"feat(scanner): graduate {module_name} to BaseScanner contract\n\n"
                f"Closes #{task.number}\n"
                f"Generated by AutonomousIssueSwarm — {cwe_id}"
            ),
        )
        if not ok:
            return ""

        return GitHubIssueSource.gh_create_pr(
            branch=task.branch,
            title=f"feat(scanner): {task.description} [auto]",
            body=(
                f"Closes #{task.number}\n\n"
                f"Auto-generated by AutonomousIssueSwarm.\n"
                f"- Scanner: `packages/cherenkov/scanners/{module_name}.py`\n"
                f"- CWE: {cwe_id}\n"
                f"- Judge: syntax ✓ | bandit ✓ | ruff ✓"
            ),
            repo=self.repo,
        )

    # ── Sprint path ──────────────────────────────────────────────────────────

    async def _run_sprint(self, task: IssueTask) -> bool:
        """Read .agents/tasks/issue-NNN.md and run AutonomousSprint."""
        if not task.task_file or not task.task_file.exists():
            logger.warning("Issue #%d has no task file, skipping.", task.number)
            self._mark_failed(task, "no task file")
            return False

        target_file = self._resolve_target_file(task.task_file)
        if not target_file:
            logger.warning("Issue #%d: could not determine target file.", task.number)
            self._mark_failed(task, "could not parse target file from task spec")
            return False

        from cherenkov.dev_crew.swarm_orchestrator import AutonomousSprint

        sprint = AutonomousSprint(
            focus_area=task.description,
            target_filepath=str(target_file),
        )
        success = await sprint.execute_sprint()

        if success:
            pr_url = self._open_pr_for_sprint(task, target_file)
            self._mark_done(task, pr_url)
            return True

        self._mark_failed(task, "sprint exhausted retries")
        return False

    def _open_pr_for_sprint(self, task: IssueTask, target_file: Path) -> str:
        ok = self._git_commit_file(
            src=target_file,
            dest=target_file,
            branch=task.branch,
            commit_msg=(
                f"{task.description}\n\nCloses #{task.number}\nGenerated by AutonomousIssueSwarm"
            ),
        )
        if not ok:
            return ""

        task_body = task.task_file.read_text() if task.task_file else ""
        return GitHubIssueSource.gh_create_pr(
            branch=task.branch,
            title=f"{task.description} [auto]",
            body=(
                f"Closes #{task.number}\n\n"
                f"Auto-generated by AutonomousIssueSwarm.\n\n"
                f"## Task spec\n{task_body[:800]}"
            ),
            repo=self.repo,
        )

    # ── Git helpers ──────────────────────────────────────────────────────────

    def _git_commit_file(
        self,
        src: Path,
        dest: Path,
        branch: str,
        commit_msg: str,
    ) -> bool:
        """
        Create branch off main, copy src→dest, commit, push.
        Serialised (no asyncio) to avoid git race conditions.
        """
        try:
            # Ensure we're on main before branching
            subprocess.run(
                ["git", "checkout", MAIN_BRANCH],
                capture_output=True,
                check=True,
            )
            subprocess.run(
                ["git", "checkout", "-b", branch],
                capture_output=True,
                check=True,
            )
            if src != dest:
                dest.parent.mkdir(parents=True, exist_ok=True)
                import shutil

                shutil.copy(src, dest)

            subprocess.run(
                ["git", "add", str(dest)],
                capture_output=True,
                check=True,
            )
            subprocess.run(
                ["git", "commit", "-m", commit_msg],
                capture_output=True,
                check=True,
            )
            subprocess.run(
                ["git", "push", "-u", "origin", branch],
                capture_output=True,
                check=True,
            )
            # Return to main
            subprocess.run(["git", "checkout", MAIN_BRANCH], capture_output=True)
            return True
        except subprocess.CalledProcessError as exc:
            logger.warning("git op failed: %s", exc.stderr.decode()[:200] if exc.stderr else exc)
            subprocess.run(["git", "checkout", MAIN_BRANCH], capture_output=True)
            return False

    # ── State & labelling ────────────────────────────────────────────────────

    def _mark_in_progress(self, task: IssueTask) -> None:
        GitHubIssueSource.upsert_issue_state(
            task.number,
            "in_progress",
            task.title,
            task.kind,
            task.branch,
        )
        GitHubIssueSource.gh_add_label(task.number, LABEL_IN_PROGRESS, self.repo)
        GitHubIssueSource.gh_comment(
            task.number,
            f"🤖 **AutonomousIssueSwarm** picked up this issue.\n"
            f"Branch: `{task.branch}` | Kind: `{task.kind}`",
            self.repo,
        )

    def _mark_done(self, task: IssueTask, pr_url: str) -> None:
        GitHubIssueSource.upsert_issue_state(
            task.number,
            "done",
            pr_url=pr_url,
        )
        GitHubIssueSource.gh_remove_label(task.number, LABEL_IN_PROGRESS, self.repo)
        GitHubIssueSource.gh_add_label(task.number, LABEL_DONE, self.repo)
        msg = (
            f"✅ PR opened: {pr_url}"
            if pr_url
            else "✅ Complete — PR creation skipped (no remote push)."
        )
        GitHubIssueSource.gh_comment(task.number, msg, self.repo)

    def _mark_failed(self, task: IssueTask, reason: str) -> None:
        GitHubIssueSource.upsert_issue_state(
            task.number,
            "failed",
            fail_reason=reason,
        )
        GitHubIssueSource.gh_remove_label(task.number, LABEL_IN_PROGRESS, self.repo)
        GitHubIssueSource.gh_comment(
            task.number,
            f"❌ **AutonomousIssueSwarm** could not complete this issue.\n"
            f"Reason: `{reason[:200]}`\nReturning to queue for manual triage.",
            self.repo,
        )

    # ── Utilities ─────────────────────────────────────────────────────────────

    def _resolve_target_file(self, task_file: Path) -> Path | None:
        """Parse the first file under 'Files to modify' in the task spec."""
        import re

        text = task_file.read_text()
        # Look for lines like: - `packages/cherenkov/...` — NEW/DEST
        matches = re.findall(r"`(packages/cherenkov/[^\s`]+\.py)`", text)
        if matches:
            return Path(matches[-1])  # prefer last (destination)
        return None

    def _report(self, batch: list[IssueTask], results: list) -> None:
        passed = sum(1 for r in results if r is True)
        logger.info(
            "Batch done: %d/%d succeeded | issues: %s",
            passed,
            len(batch),
            [f"#{t.number}({'ok' if r is True else 'fail'})" for t, r in zip(batch, results)],
        )


# ── CLI entry point ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys

    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

    repo = next((a for a in sys.argv[1:] if "/" in a), "")
    swarm = AutonomousIssueSwarm(repo=repo)

    if "--once" in sys.argv:
        tasks = swarm.source.fetch_pending(limit=1)
        if tasks:
            result = asyncio.run(swarm._execute(tasks[0]))
            print(f"Result: {'ok' if result else 'failed'}")
        else:
            print("No actionable issues found.")
    else:
        asyncio.run(swarm.run_forever())
