"""
Auto-generated by autonomous agents
Source: batch_1_20260501_130019.txt
Category: misc
"""

import requests


class WebhookNotifications:
    """
    A class to send webhooks to notify about events using webhook mechanism.
    Raises an exception if the request fails.

    Attributes:
        url (str): The URL of the target endpoint for the webhook notifications.
            It should be a valid URL which accepts POST or JSON requests.
    """

    def __init__(self, url: str):
        """
        Initialize WebhookNotifications with the given URL.

        Args:
            url (str): The target webhook endpoint URL.

        Raises:
            ValueError: If the provided URL is not in the correct format.
        """
        self.url = url
        if not self.is_valid_url():
            raise ValueError(f"Invalid URL: {self.url}")

    def is_valid_url(self) -> bool:
        """
        Checks if the provided URL is valid.

        Returns:
            bool: True if the URL is valid, False otherwise.
        """
        try:
            result = requests.head(self.url)
            return result.status_code == 200
        except Exception as e:
            print(f"Warning: Failed to validate URL with head request. {e}")
            return False

    def send_notification(self, event_data) -> None:
        """
        Sends the provided data as a POST payload to the configured webhook.

        Args:
            event_data (dict): The data to be sent in the body of the POST request.

        Returns:
            bool: True if the send operation is successful, False otherwise and raises an exception on failure.
        """
        try:
            result = requests.post(self.url, json=event_data)
            return 200 <= result.status_code < 300
        except Exception as e:
            print(
                f"Warning: There was a problem with the HTTP request to {self.url}. Error details: {str(e)}"
            )
            raise


def example_usage():
    """
    Example usage of WebhookNotifications.

    Returns:
        None
    """
    url = "https://example.com/webhooks"
    wn = WebhookNotifications(url)

    # Correct usage with valid event data dictionary
    try:
        if wn.send_notification({"key": "value"}):
            print("Notification sent successfully")
    except ValueError as e:
        print(f"ValueError: {e}")
    except Exception as e:
        print(f"Unexpected error: {str(e)}")


def check_tests():
    """
    Placeholder for unit tests. Production-ready code does not usually include such tests,
    but for the sake of this task, it will be included in a simplistic form.

    Returns:
        None
    """
    # Simple test setup and verification (mock function usage if needed with assertions)
    assert "200" in example_usage()


if __name__ == "__main__":
    example_usage()
