"""
Auto-generated by autonomous agents
Source: batch_1_20260501_122822.txt
Category: misc
"""

import requests


class WebhookNotification:
    """
    This class manages sending webhook notifications with error handling and docstrings.

    Example Usage:
    >>> notification = WebhookNotification("https://webhook.site")
    >>> notification.notify("This is a test message.")

    Attributes:
        webhook_url (str): The URL to send the webhooks to.

    Methods:
        notify(message: str) -> None: Sends a message via a webhook. Raises an exception if there's a network issue or invalid response from the webhook server.
    """

    def __init__(self, webhook_url: str):
        """
        Initializes the class with a valid webhook URL.

        Args:
            webhook_url (str): The URL to send webhooks to.

        Returns:
            None

        Raises:
            ValueError: If the provided URL is None or an empty string.
        """
        if not webhook_url:
            raise ValueError("Webhook URL must be set.")
        self.webhook_url = webhook_url

    def notify(self, message: str) -> None:
        """
        Sends a notification via a webhook to the configured server URL.

        Args:
            message (str): The message to send as part of the notification payload.

        Returns:
            None

        Raises:
            requests.RequestException: If there is an issue connecting to or receiving data from the webhook URL.
            ValueError: If the incoming message body cannot be serialized to JSON.
        """
        headers = {"Content-Type": "application/json"}
        try:
            response = requests.post(self.webhook_url, json={"message": message}, headers=headers, timeout=10)
            response.raise_for_status()  # Raises an error for bad HTTP responses
        except requests.RequestException as e:
            raise requests.RequestException(f"Failed to send webhook: {e}")
        else:
            if not response.json():
                raise ValueError("The webhook server did not return a valid JSON object.")


# Example usage of the class
if __name__ == "__main__":
    notification = WebhookNotification("https://webhook.site")
    try:
        notification.notify("Sample Notification Message.")
    except Exception as e:
        print(f"An error occurred: {e}")
