name: Feature Request
description: Suggest an idea for this project
title: "[FEAT] "
labels: ["feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting a feature!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - priority:high
        - priority:medium
        - priority:low
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      multiple: true
      options:
        - area:scanner
        - area:orchestrator
        - area:ui
        - area:api
        - area:docs
        - area:infra
        - area:agent
        - area:security
