version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Africa/Cairo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      python-dependencies:
        update-types:
          - "minor"
          - "patch"
