"""
Auto-generated by autonomous agents
Source: batch_1_20260501_054345.txt
Category: scanners
"""

#!/usr/bin/env python

import base64
import xml.sax
from xml.sax.handler import feature_external_ges, feature_external_pes
import io
import re


class XXESS(object):
    """
    A class to scan XML documents for potential XXE (XML External Entity) vulnerabilities.

    Methods:
        check_external_entity(self, xml_input): Check if the provided XML document contains any external entities.
    """

    def __init__(self, base64_decode=True):
        """
        Initialize the XXESS instance.

        Args:
            base64_decode (bool): A flag indicating whether to base64 decode XML before checking.
        """
        self.base64_decode = base64_decode

    def _decode_base64(self, xml_input):
        if isinstance(xml_input, bytes):
            try:
                xml_input = xml_input.decode("utf-8")
            except UnicodeDecodeError:
                raise ValueError("XML Input must be a valid UTF-8 string.")

        if not isinstance(xml_input, str) or not xml_input.startswith("base64,"):
            raise ValueError("XML Input must be a valid base64 encoded string.")

        part = xml_input[7:]  # Remove 'base64,' prefix
        try:
            decoded_data = base64.b64decode(part)
            return decoded_data.decode("utf-8")
        except Exception as e:
            raise ValueError(f"Failed to decode base64: {e}")

    def check_external_entity(self, xml_input):
        """
        Checks for XXE vulnerabilities using heuristic and SAX parsing.

        Args:
            xml_input (str or bytes): The XML content to be scanned.

        Returns:
            bool: True if potential XXE vulnerability is detected, False otherwise.
        """
        try:
            if self.base64_decode and (
                isinstance(xml_input, str) and xml_input.startswith("base64,")
            ):
                xml_input = self._decode_base64(xml_input)
            elif isinstance(xml_input, bytes):
                xml_input = xml_input.decode("utf-8")

            # Heuristic check for DOCTYPE or ENTITY
            if re.search(r"<!DOCTYPE", xml_input, re.IGNORECASE) or re.search(
                r"<!ENTITY", xml_input, re.IGNORECASE
            ):
                return True

            # Secure parsing with SAX
            parser = xml.sax.make_parser()
            # Disable external entities
            parser.setFeature(feature_external_ges, False)
            parser.setFeature(feature_external_pes, False)

            # We use a dummy handler as we only care if it parses without errors
            # and our heuristic already covers most XXE attempts.
            handler = xml.sax.ContentHandler()
            parser.setContentHandler(handler)

            input_source = xml.sax.xmlreader.InputSource()
            input_source.setByteStream(io.BytesIO(xml_input.encode("utf-8")))
            parser.parse(input_source)

            return False
        except (xml.sax.SAXParseException, ValueError, TypeError):
            # If it's malformed XML or other issues, we treat it as potentially dangerous
            # or simply not a valid safe XML.
            return True
        except Exception:
            return True

    def test(self):
        """
        A convenience method to run some tests.
        """
        # Test 1: Valid XML
        valid_xml = b'<?xml version="1.0" encoding="UTF-8"?><root>Valid content</root>'
        assert self.check_external_entity(valid_xml) is False

        # Test 2: Encoded malicious XML input that mimics a XXE
        # Using a proper base64 encoded XXE for the test
        xxe_payload = '<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><foo>&xxe;</foo>'
        encoded_malicious_xml = "base64," + base64.b64encode(xxe_payload.encode()).decode()
        result = self.check_external_entity(encoded_malicious_xml)
        assert result is True


xxes_tests = [
    (b'<?xml version="1.0" encoding="UTF-8"?><root>Valid content</root>', False),
    ("base64," + base64.b64encode(b'<!DOCTYPE foo [<!ENTITY xxe "bar">]><foo>&xxe;</foo>').decode(), True),
]

XXEScannerError = type(
    "XXEScannerError",
    (Exception,),
    {
        "__init__": lambda self, msg: setattr(self, "msg", msg),
        "__str__": lambda self: self.msg,
    },
)


def test_scanner():
    scanner = XXESS()
    for xml_input, expected_result in xxes_tests:
        result = scanner.check_external_entity(xml_input)
        if result != expected_result:
            raise AssertionError(
                f"Check for XXE in {xml_input} did not return {expected_result}. Result: {result}"
            )
    print("Tests passed!")


if __name__ == "__main__":
    test_scanner()
