services:
  dvwa:
    image: ghcr.io/digininja/dvwa:latest
    ports:
      - "80:80"
    environment:
      - DB_SERVER=db
      - DB_USER=dvwa
      - DB_PASSWORD=p@ssw0rd
      - DB_DATABASE=dvwa
    depends_on:
      - db
  db:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
