"""
Auto-generated by autonomous agents
Source: batch_1_20260501_114614.txt
Category: scanners
"""

import aiohttp

from cherenkov.core.base_scanner import BaseScanner, Finding, ScanResult, Severity


class CVEDatabaseScanner(BaseScanner):
    name = "CVEDatabaseScanner"
    description = "Retrieves vulnerabilities from the CVE database."
    tags = ["cve", "passive"]

    def __init__(self) -> None:
        super().__init__(name=self.name, description=self.description)
        self.base_url = "https://api.example-cve-database.com/v2"

    async def scan(self, target: str, timeout: float = 10.0) -> ScanResult:
        findings: list[Finding] = []
        try:
            # Here target acts as a package name or identifier to query.
            vulnerabilities = await self.get_vulnerabilities(target, max_results=50, severity="HIGH")
            for vuln in vulnerabilities:
                findings.append(
                    Finding(
                        title=f"CVE Found for {target}",
                        description=str(vuln),
                        severity=Severity.HIGH,
                        cwe="CWE-1395",
                        remediation="Update or remove vulnerable components.",
                    )
                )
        except Exception:
            import logging
            logging.warning("CVE Database scan failed")

        return ScanResult(scanner_name=self.name, target=target, findings=findings)

    async def get_vulnerabilities(self, package: str, max_results: int = 50, severity: str = None):
        """
        Retrieves a list of CVEs from the database based on optional query parameters.
        """
        params = {"package": package}
        if severity and severity.lower() not in ("low", "medium", "high"):
            raise ValueError("Valid severities are: 'LOW', 'MEDIUM', or 'HIGH'")
        if max_results > 100:
            raise ValueError("Max results cannot exceed 100")

        params["max"] = max_results
        if severity is not None:
            params["min_severity"] = severity

        async with aiohttp.ClientSession() as session:
            async with session.get(f"{self.base_url}/list", params=params, timeout=10) as response:
                if response.status != 200:
                    return []

                try:
                    content = await response.json()
                    return content.get("results", [])
                except ValueError as e:
                    raise ValueError("Failed to parse JSON data from the API") from e

