"""
Auto-generated by autonomous agents
Source: batch_1_20260501_054208.txt
Category: scanners
"""

import os

from cherenkov.core.base_scanner import BaseScanner, Finding, ScanResult, Severity


class PathTraversalScanner(BaseScanner):
    name = "PathTraversalScanner"
    description = "Detects path traversal vulnerabilities"
    tags = ["web", "active"]

    def __init__(self) -> None:
        super().__init__(name=self.name, description=self.description)

    async def scan(self, target: str, timeout: float = 10.0) -> ScanResult:
        findings: list[Finding] = []

        try:
            res = self._scan_path(target, root=target)
            if not res["safe"]:
                for unsafe in res.get("unsafe_paths", []):
                    findings.append(
                        Finding(
                            title="Path Traversal Vulnerability",
                            description=f"Unsafe path access detected: {unsafe}",
                            severity=Severity.HIGH,
                            evidence={"unsafe_path": unsafe},
                            cwe="CWE-22",
                            remediation="Ensure user inputs are properly sanitized and validated against allowed paths."
                        )
                    )
        except Exception as e:
            print("Exception:", e)
            pass

        return ScanResult(scanner_name=self.name, target=target, findings=findings)

    def _scan_path(self, directory: str, root: str) -> dict:
        """
        Internal method to perform actual file/directory scanning within a given directory.

        :param directory: Directory to scan
        :return: A dictionary containing information about files and directories found in the specified directory (including subdirectories for safety checking if found)
        """
        result = {"safe": True, "files_and_dirs": [], "unsafe_paths": []}
        try:
            entries = [entry.path for entry in os.scandir(directory) if not entry.is_dir()]
            result["files_and_dirs"] = sorted(entries, key=lambda x: x[1:])
            for file_or_dir_path in entries:
                full_path = os.path.join(directory, file_or_dir_path)
                if not self._is_safe(full_path, root):
                    result["unsafe_paths"].append(full_path)
                    result["safe"] = False
        except PermissionError as e:
            raise ValueError(
                f"PermissionDenied: You do not have access to the directory '{directory}'"
            ) from e
        except Exception as e:
            raise ValueError(f"An error occurred while processing the path: {directory}") from e

        return result

    def _is_safe(self, full_path: str, root: str) -> bool:
        """
        Helper method that checks if the given file or directory is considered safe.

        :param full_path: The complete file path to be checked
        :return: True if the file or directory is deemed safe (within current root), otherwise False
        """
        return os.path.commonprefix([root, full_path]) == root

