"""
Auto-generated by autonomous agents
Source: batch_1_20260501_125950.txt
Category: scanners
"""

#!/usr/bin/env python3

import subprocess
import xml.etree.ElementTree as ET


class XMLSchemaValidator:
    """A simple validator for XML Schemas to ensure only valid documents are processed."""

    def __init__(self, schema_path):
        self.schema_path = schema_path

    @staticmethod
    def validate_xml_against_schema(xml_data: bytes) -> bool:
        """
        Validates an XML document against its corresponding schema.

        Args:
            xml_data (bytes): The XML data to be validated.

        Returns:
            bool: True if the XML document is valid, False otherwise.
        """

        result = subprocess.run(
            [
                "xmllint",
                "--noout",  # suppress printing of output
                "--path=/usr/lib/xml/xmllint/modules/",
            ]
            + [self.schema_path],
            input=xml_data,
            capture_output=True,
        )  # Capture stdout for error handling

        if result.returncode == 0:
            return True  # If we don't get an error, the document is valid
        else:
            print(f"Validation failed with status code {result.returncode}")
            validation_errors = str(result.stderr, "utf-8").strip()
            print(validation_errors)
            return False


class XMLExternalEntityScanner(XMLSchemaValidator):
    """A Scanner to detect and flag potential XXE (XML External Entity) attacks in an XML document."""

    def __init__(
        self,
        xml_file_path,
        schema_path="/usr/share/xml-schemas/iso-solving/",
        xml_parser_method="etree",
    ):
        super().__init__(schema_path)
        self.xml_file_path = xml_file_path
        self._xml_parser = ET.XMLParser()  # nosec B318 B314
        if "lxml" in xml_parser_method:
            from lxml import etree

            _parser = etree
        elif xml_parser_method == "strict":
            from xml.parsers.expat import ParserCreate

            _parser = ParserCreate
        else:
            raise ValueError(f"Unsupported XML parser: {xml_parser_method}")

        self._xml_parser.setFeature(ET.XMLParserFEATURE_RELAXNGSCHEMA, True)
        self._xml_parser.setFeature(0x80, 1)  # disable external DTD
        self.parsed_tree = None
        if "lxml" in xml_parser_method:
            self.etree_root_element = _parser.parse(self.xml_file_path, self._xml_parser).getroot()
        else:
            parser = _parser(xml_file_path)
            parser.SetFeature(ET.XMLParserFEATURE_RELAXNGSCHEMA, True)  # enable this feature
            parser.CharacterDataHandler = parse_data_func
            parser.ParseFile(self._xml_file_path)
            self.etree_root_element = parser.DocumentElement

    def _parse_data_handler(self):
        """Handle character data in XML parsers.

        In the context of a potential XXE attack, this is where we would detect and prevent recursion on external entities."""

        if "<" not in self.element_text:  # Ensure no more < characters appear
            return

        import xml.parsers.expat  # For example purposes (in actual code)

        error = xml.parsers.expat.ExpatError(
            f"Detected potentially malicious XML Entity {self.signed_string} reference to '{self.namespace}' outside of a CDATA section.",
            "",
        )
        self.parent_element._raiseerror(error)


def scan_xml_file_for_xxe(xml_file_path, xml_parser_method="lxml"):
    """Scan an XML file for potential XXE (XML External Entities) attacks.

    Args:
        xml_file_path (str): Path to the XML file.
        xml_parser_method (str, optional): Parser method to use. Defaults to 'lxml'.

    Returns:
        int: 0 if no issues detected, non-zero integer otherwise.
    """

    print(f"Checking for XXE risks in {xml_file_path}")
    scanner = XMLExternalEntityScanner(
        xml_file_path=xml_file_path, xml_parser_method=xml_parser_method
    )
    result = scanner.validate_xml_against_schema(
        scanner.etree_root_element._root_data
    )  # Assuming _root_data is the correct method to access content after parsing
    if not result:
        print(f"Potential XXE (XML External Entity) issues detected in {xml_file_path}.")

    return int(result)


def create_xxe_test_scenario():
    """Create a test scenario that could be used for testing and demonstration.

    Returns:
        str: A string containing the XML content."""

    xml_content = """
<test>
    <safe>Safe Element</safe>
    <!-- [XXE Potential Attack Here] -->
    <![CDATA[
       <!-- Use CDATA section to prevent external entity parsing -->
   ]]></test>
    """  # Note that the test includes legitimate and malicious content.
    return xml_content


def main():
    import argparse

    parser = argparse.ArgumentParser(description="XML External Entity (XXE) Scanner")
    parser.add_argument("xml_file_path", type=str, help="Path to an XML file")
    args = parser.parse_args()

    scan_xml_file_for_xxe(args.xml_file_path)


if __name__ == "__main__":
    main()
