"""
Auto-generated by autonomous agents
Source: batch_1_20260503_033246.txt
Category: scanners
"""

import re

import aiohttp

from cherenkov.core.base_scanner import BaseScanner, Finding, ScanResult, Severity


class XXEScanner(BaseScanner):
    name = "XXEScanner"
    description = "Detects XML External Entity (XXE) vulnerabilities."
    tags = ["web", "active"]

    def __init__(self) -> None:
        super().__init__(name=self.name, description=self.description)

    async def scan(self, target: str, timeout: float = 10.0) -> ScanResult:
        findings: list[Finding] = []

        try:
            # Assuming target is a URL to fetch XML from.
            async with aiohttp.ClientSession() as session:
                async with session.get(target, timeout=timeout) as response:
                    if response.status == 200:
                        xml_content = await response.text()
                        vulnerabilities = self.perform_scan(xml_content)
                        for vuln in vulnerabilities:
                            findings.append(
                                Finding(
                                    title="XXE Vulnerability",
                                    description=f"Detected XXE Vulnerability: {vuln.get('entity_name')}, value {vuln.get('_value')}",
                                    severity=Severity.HIGH,
                                    cwe="CWE-611",
                                    remediation="Disable external entity resolution in XML parsers."
                                )
                            )
        except Exception:
            import logging
            logging.warning("XXE scan failed")

        return ScanResult(scanner_name=self.name, target=target, findings=findings)

    def perform_scan(self, xml_content):
        """
        This function performs an XML External Entity (XXE) scan on the given XML content.

        Args:
            xml_content (str): The XML string to be scanned for XXE vulnerabilities.

        Returns:
            list: A list of potential vulnerable entities found in the input. Each vulnerability is represented as a dictionary with keys 'entity_name' and '_value'.
        """
        potential_vulnerabilities = []

        # Check if the XML content starts with <?xml
        if not xml_content.startswith("<?xml"):
            raise ValueError("XML declaration is missing in the input.")

        while True:
            start_tag_regex = re.compile(r"<" + r"\?.*\?>", re.IGNORECASE)
            match = start_tag_regex.search(xml_content, 1)
            if match is None:
                break

            # Extract the XXE entity name and its value
            entity_start = match.group().replace("?", "").strip()

            entity_end_index = entity_start.index("?")
            entity_value = xml_content[entity_start.index("?") + 3 : entity_end_index]
            entity_name = entity_start[: entity_start.index("?")]

            # Log the finding as a potential vulnerability
            potential_vulnerabilities.append({"entity_name": entity_name, "_value": entity_value})

            xml_content = xml_content[match.end() :].strip()

        return potential_vulnerabilities

