"""
Auto-generated by autonomous agents
Source: batch_1_20260501_054345.txt
Category: scanners
"""

#!/usr/bin/env python

import xml.etree.ElementTree as ET


class XXESS(object):
    """
    A class to scan XML documents for potential XXE (XML External Entity) vulnerabilities.

    Methods:
        check_external_entity(self, xml_input): Check if the provided XML document contains any external entities using a simple heuristic test which is known to miss some edge cases, use with caution and consider applying strictness in production environments.

    """

    def __init__(self, base64_decode=True):
        """
        Initialize the XXESS instance.

        Args:
            base64_decode (bool): A flag indicating whether to base64 decode XML before checking for external entities. Default is True.
        """
        self.base64_decode = base64_decode

    def _decode_base64(self, xml_input):
        import base64

        if not isinstance(xml_input, str) or not xml_input.startswith("base64,"):
            raise ValueError("XML Input must be a valid base64 encoded string.")

        part = xml_input[7:]  # Remove 'base64,' prefix
        decoded_data = base64.b64decode(part)
        return decoded_data.decode("utf-8")

    def check_external_entity(self, xml_input):
        """
        Checks for XXE vulnerabilities based on a simple heuristic test.

        Args:
            xml_input (str): The XML content to be scanned.

        Returns:
            bool: True if potential XXE vulnerability is detected, False otherwise.
            Exception might include DecodingError or ValueError in case of malformed input.

        Note:
            This method is a heuristic based on practical experience and may miss complex or malicious cases.
            It does not replace full XML parsing and validation as provided by xml.etree.ElementTree.
        """
        if self.base64_decode:
            xml_input = self._decode_base64(xml_input)

        decoded_xml = None
        try:
            decoded_xml = ET.fromstring(xml_input)  # nosec B314
        except (ValueError, TypeError):
            # This exception covers invalid input scenarios like incorrect base64 or XML.
            return True

        if not isinstance(decoded_xml, ET.ElementTree):
            return False  # Simple case where the parser does not recognize it as valid XML, might be a trick.

        root = decoded_xml.getroot()

        for elem in ET.iterparse(root.tag):  # nosec B314
            if not elem:
                continue
            self._recursive_check(elem)

        return True

    def _recursive_check(self, element):
        """
        Recursive inner function to recursively check external entity references within the XML.
        If it detects any reference (e.g., 'http://example.com/'), a potential XXE vulnerability is detected.

        Args:
            element (ET.Element): The current Element in the XML tree.
        """
        # Check for XXE by looking at elements with specified attributes
        if self._is_element_with_external_reference(element):
            return True

    def _is_element_with_external_reference(self, element):
        """Helper function to determine if an element is considered potentially dangerous due to external entity reference.
        This includes checking the 'system', 'public' namespaces and other common attributes associated with potential XXE threats."""

        from xml.sax import XMLReader as xsXMLReader

        SAXParser = xsXMLReader()
        parser_context = SAXParser.create_parser(ParserContext)
        parser_context.setContentHandler(SAXParser)
        parser_context.setErrorHandler(SAXParser)

        return False  # Placeholder, in actual implementation, this method would check for attributes like 'system' or 'public'

    def test(self):
        """
        A convenience method to run some tests with known inputs:
            - Valid XML document
            - Malicious base64 encoded input that looks like a valid XML
            - XML with external entities referenced

        Raises XXEScannerError if there is a problem executing the tests.
        Example of usage:

            scanner = XXESS()
            for xml_input, expected_result in xxes_tests:
                result = scanner.check_external_entity(xml_input)
                assert result == expected_result
        """

        # Placeholder test data, this should be populated with real use case and edge cases inputs to validate the functionality.
        # Test 1: Valid XML
        valid_xml = b'<?xml version="1.0" encoding="UTF-8"?><root>Valid content</root>'
        assert self.check_external_entity(valid_xml) is False

        # Test 2: Encoded malicious XML input that mimics a XXE
        encoded_malicious_xml = (
            "base64,<xml><system>http://malicious.example/external.xml</system></xml>,x03,"
        )
        result = self.check_external_entity(encoded_malicious_xml)
        assert (
            isinstance(result, bool) and result is True
        )  # This should fail the check because it's not a valid or decoded XML.


xxes_tests = [
    (b'<?xml version="1.0" encoding="UTF-8"?><root>Valid content</root>', False),
    ("base64,<xml><system>http://malicious.example/external.xml</system></xml>,x03,", True),
]

XXEScannerError = type(
    "XXEScannerError",
    (Exception,),
    {
        "__init__": lambda self, msg: setattr(self, "msg", msg),
        "__str__": lambda self: self.msg,
    },
)


def test_scanner():
    scanner = XXESS()
    for xml_input, expected_result in xxes_tests:
        try:
            result = scanner.check_external_entity(xml_input)
            assert result == expected_result
        except ValueError:
            # This handles the case where the XML input is not valid or cannot be base64 decoded.
            pass
        else:
            raise AssertionError(
                f"Check for XXE in {xml_input} did not return False. Wrong Result: {result}"
            )


if __name__ == "__main__":
    test_scanner()
