"""
SQL Injection Scanner
Auto-generated by cherenkov Autonomous Developer Crew
"""

import requests
import urllib.parse


def sql_injection_scan(api_url, input_value):
    """
    Scan for SQL injection vulnerabilities

    Args:
        api_url (str): Target API endpoint URL
        input_value (str): Input value to test for injection

    Returns:
        bool: True when scan completes
    """
    # Safely decode user input values to avoid unintended encoding vulnerabilities
    sanitized_input = urllib.parse.quote_plus(input_value)

    # Common SQL errors that could indicate vulnerability
    error_responses = (
        "Error: SQLDataAccessException",
        "Error: Invalid SQL statement",
        "Error parsing request",
    )

    # Pre-generated payloads for various injection techniques
    sql_payloads = [
        f"AND (SELECT 1) -- {sanitized_input}",
        f"' OR '1'='1' -- {sanitized_input}",
        f"UNION SELECT NULL -- {sanitized_input}",
    ]

    vulnerabilities_found = []

    # Loop through each payload and try to execute a SQL query
    for sql_payload in sql_payloads:
        query = (
            f"SELECT * FROM vulnerable_table WHERE column_name LIKE '%{sql_payload}%'"
        )

        try:
            response = requests.get(f"{api_url}/{query}", timeout=5)

            # Check if standard SQL errors contain specific error codes related to payload injection
            for err_response in error_responses:
                if (
                    "syntax" in str(err_response).lower()
                    or "failed" in err_response.lower()
                ):
                    print(f"⚠️  SQL Injection possible at {sql_payload}")
                    vulnerabilities_found.append(sql_payload)

        except requests.exceptions.RequestException as e:
            print(f"❌ Request error: {e}")

        except (requests.Timeout, requests.ConnectionError) as ce:
            print(f"🔌 {ce}: Connection problem detected when testing the SQL query.")

    if vulnerabilities_found:
        print(f"\n🚨 Found {len(vulnerabilities_found)} potential vulnerabilities!")
        return False
    else:
        print(f"\n✅ No SQL injection vulnerabilities detected")
        return True


if __name__ == "__main__":
    print("=" * 70)
    print("SQL Injection Scanner - cherenkov")
    print("=" * 70)

    # Example usage
    # sql_injection_scan("http://example.com/api", "test_input")
    print("\nUsage: sql_injection_scan(api_url, input_value)")

