"""
Auto-generated by autonomous agents
Source: batch_1_20260503_045615.txt
Category: api
"""

import os

import requests


class SlackDiscordAPI:
    """
    A class to interact with the Slack or Discord API.

    Attributes:
        url: Base URL for the API (e.g., 'https://slack.com/api')
        token: Token for authentication (should be set as an environment variable)
        method: Method for making requests ('GET' by default)
    """

    def __init__(self, method="GET"):
        self.url = os.getenv("API_URL", "")
        self.token = os.getenv("TOKEN", "")
        if not self.url or not self.token:
            raise ValueError("URL and TOKEN environment variables are required.")

        self.method = method
        if self.method.upper() != "GET" and self.method.upper() != "POST":
            raise ValueError(
                "Only GET and POST methods are supported. Use 'GET' for most use cases."
            )

    def make_request(self, endpoint, data=None):
        headers = {"Authorization": f"Bearer {self.token}"}

        if self.method.upper() == "GET":
            resp = requests.get(f"{self.url}{endpoint}", headers=headers)
        else:
            resp = requests.post(f"{self.url}{endpoint}", headers=headers, json=data)

        if not resp.ok:
            raise Exception(
                f"Request to {resp.url} failed. Status code: {resp.status_code}, Response: {resp.text}"
            )

        return resp.json()


class SlackClient(SlackDiscordAPI):
    """
    Class to interact with the Slack API.

    Example of usage:
    client = SlackClient(token="your-slack-token", method='POST')
    response = client.make_request('/channels.list', {'exclude_archived': True})
    print(response)
    """

    def __init__(self, token: str, **kwargs):
        super().__init__("POST")  # Most operations for Slack use POST
        self.url = "https://slack.com/api/"
        self.token = token


class DiscordClient(SlackDiscordAPI):
    """
    Class to interact with the Discord API. Use GET and POST with appropriate endpoints.

    Example of usage:
    client = DiscordClient(token="your-discord-token", method='GET')
    response = client.make_request('/users/@me', {'include_client)': True})
    print(response)
    """

    def __init__(self, token: str, **kwargs):
        super().__init__("GET")  # Most operations for Discord use POST
        self.url = "https://discord.com/api/v8"
        self.token = token


def main():
    slack_token = os.environ.get("SLACK_TOKEN")
    discord_token = os.environ.get("DISCORD_TOKEN")

    slack_client = SlackClient(slack_token)
    discord_client = DiscordClient(discord_token)

    # Example of usage - List all channels in a Slack workspace
    response = slack_client.make_request("/channels.list", {"exclude_archived": True})
    print("Slack Channels:", response)

    # Example of usage - Get the current user's info from Discord
    response = discord_client.make_request("/users/@me")
    print("Discord User Info:", response)


if __name__ == "__main__":
    main()
